@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "User" as User
participant ":HTTPClient" as http
participant ":ACME" as acme
participant ":SMTP" as smt
participant ":EmailClient" as email
actor "Moderador" as mod


User --> http: Create Tmeporary vote
http --> acme: POST/votes/voteProduct
activate acme
acme --> http: 202
deactivate acme
acme --> smt: sendEmail(UserEmail)
activate smt
smt --> acme: ok
deactivate smt
acme --> smt: sendEmail(ModeratorEmail)
activate smt
smt --> acme: ok
deactivate smt

User --> email: getEmails()
email --> smt: getEmails()
smt --> email: emails
email --> User: emails


mod --> email: getEmails()
email --> smt: getEmails()
smt --> email: emails
email --> mod: emails
mod --> http: Approve review
http --> acme: POST/reviews/{{reviewId}}/approve/true
activate acme
acme --> http: ok
deactivate acme
acme --> smt: sendEmail(UserEmail)
activate smt
smt --> acme: ok
deactivate smt

@enduml
