@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

participant ":UIVote_Q" as vote
participant ":Vote_Q" as vote1

vote -> vote1: GET/votes/{reviewId}/{userId}
vote1 --> vote: Vote
@enduml